development:
  adapter: mysql2
  encoding: utf8
  database: lunch_development
  username: root
  password: esperoel2013
  
test:
  adapter: mysql2
  encoding: utf8
  database: lunch_test
  username: travis
  password: esperoel2013

production:
  adapter: mysql2
  encoding: utf8
  database: lunch
  username: root
  password: esperoel2013
