development:
  adapter: sqlite3
  encoding: utf8
  database: lunch_development

test:
  adapter: sqlite3
  encoding: utf8
  database: lunch_test

production:
  adapter: sqlite3
  encoding: utf8
  database: lunch
